name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: |
        cd Backend
        mvn clean package -DskipTests
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Stop existing application
          sudo pkill -f "Theinvincibles-0.0.1-SNAPSHOT.jar" || true
          
          # Remove old jar
          rm -f ~/Theinvincibles-0.0.1-SNAPSHOT.jar
          
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "Backend/target/Theinvincibles-0.0.1-SNAPSHOT.jar"
        target: "~/"
        strip_components: 2
        
    - name: Start Application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Start application in background
          nohup java -jar ~/Theinvincibles-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          
          # Wait a moment and check if it's running
          sleep 10
          if pgrep -f "Theinvincibles-0.0.1-SNAPSHOT.jar" > /dev/null; then
            echo "Application started successfully"
          else
            echo "Application failed to start"
            exit 1
          fi
