name: Testing and Deploy
on:
  push:
    branches: [ main, auth-feature ]
  pull_request:
    branches: [ main, auth-feature ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    # Backend Testing
    - name: Set up JDK 17
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Create Firebase service account file (mock)
      run: |
        mkdir -p Backend/src/main/resources/config
        cat > Backend/src/main/resources/config/firebase-service-account.json << 'EOF'
        {
          "type": "service_account",
          "project_id": "mock-project",
          "private_key_id": "mock-key-id-123",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMOCK_PRIVATE_KEY_FOR_TESTING_ONLY\n-----END PRIVATE KEY-----",
          "client_email": "mock-service-account@mock-project.iam.gserviceaccount.com",
          "client_id": "123456789"
        }
        EOF
    
    - name: Run Backend tests with coverage
      run: |
        cd Backend
        mvn clean verify -Dspring.profiles.active=test
      env:
        SPRING_PROFILES_ACTIVE: test
    
    - name: Upload Backend coverage to Codecov
      uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
      with:
        files: ./Backend/target/site/jacoco/jacoco.xml
        flags: backend
        name: backend-coverage
        token: ${{ secrets.CODECOV_TOKEN }}
    
    # Frontend Testing
    - name: Set up Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: '20'
    
    - name: Install Frontend dependencies
      run: |
        cd frontend
        npm install react-scripts
        npm ci
    
    - name: Run Frontend tests with coverage
      run: |
        cd Frontend
        npm run test:coverage
    
    - name: Upload Frontend coverage to Codecov
      uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
      with:
        files: ./Frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Only deploy on push to main or auth-feature (not on PRs)
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/auth-feature')
    
    steps:
    - name: Trigger Render Deploy
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl -X POST "$RENDER_DEPLOY_HOOK_URL"
