name: Testing and Coverage

on:
  push:
    branches: [ main, dev, auth-feature ]
  pull_request:
    branches: [ main, dev, auth-feature ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Create Firebase service account file (mock)
      run: |
        mkdir -p Backend/src/main/resources/config
        echo '{"type":"service_account","project_id":"test","private_key_id":"test","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhki...\n-----END PRIVATE KEY-----","client_email":"test@test.iam.gserviceaccount.com","client_id":"test"}' \
          > Backend/src/main/resources/config/firebase-service-account.json

    - name: Run tests with coverage
      run: |
        cd Backend
        mvn clean verify -Dspring.profiles.active=ci
      env:
        SPRING_PROFILES_ACTIVE: ci

    - name: List generated reports
      run: |
        echo "Surefire reports:"
        find Backend/target/surefire-reports -name "*.xml" || true
        echo "Jacoco reports:"
        find Backend/target/site/jacoco -name "*.xml" || true

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: 'Backend/target/surefire-reports/*.xml'
        reporter: java-junit
        fail-on-error: false

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./Backend/target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true

    - name: Comment coverage on PR
      uses: madrapps/jacoco-report@v1.6.1
      if: github.event_name == 'pull_request'
      with:
        paths: |
          ${{ github.workspace }}/Backend/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 70
        min-coverage-changed-files: 80
        title: Code Coverage Report
        update-comment: true

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
