name: Testing and Coverage

on:
  push:
    branches: [ main, dev, auth-feature ]
  pull_request:
    branches: [ main, dev, auth-feature ]

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven' 

    - name: Create Firebase service account file (mock)
      run: |
        mkdir -p Backend/src/main/resources/config
        echo '{"type":"service_account","project_id":"test","private_key_id":"test","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7W8jYbF8x9vKq\n-----END PRIVATE KEY-----","client_email":"test@test.iam.gserviceaccount.com","client_id":"test"}' \
          > Backend/src/main/resources/config/firebase-service-account.json

    - name: Run tests with coverage
      run: |
        cd Backend
        mvn clean verify -Dspring.profiles.active=ci
      env:
        SPRING_PROFILES_ACTIVE: ci

    - name: List generated reports
      if: always()
      run: |
        echo "Surefire reports:"
        find Backend/target/surefire-reports -name "*.xml" 2>/dev/null || echo "No surefire reports found"
        echo ""
        echo "Jacoco reports:"
        find Backend/target/site/jacoco -name "*.xml" 2>/dev/null || echo "No jacoco reports found"

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          Backend/target/surefire-reports/*.xml
        check_name: Maven Test Results
        comment_mode: off

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./Backend/target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true

    - name: Comment coverage on PR
      uses: madrapps/jacoco-report@v1.6.1
      if: github.event_name == 'pull_request'
      with:
        paths: |
          ${{ github.workspace }}/Backend/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 70
        min-coverage-changed-files: 80
        title: Code Coverage Report
        update-comment: true

    - name: Upload test reports as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          Backend/target/surefire-reports/
          Backend/target/site/jacoco/
        retention-days: 30

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    if: always()  # Run even if tests fail
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
